/* ============================================================
   LAWS OF CYBERSECURITY — DATA FILE
   Every entry below reflects an established, citable principle
   from the security, cryptography, privacy, or forensics
   literature. Origins are noted where a single formulator
   exists; many are consensus principles refined by the field.
   ============================================================ */

const CATEGORIES = [
  { id: "foundational", label: "Foundational Principles", color: "#F0A83C" },
  { id: "access",       label: "Access & Trust",           color: "#4FC3D9" },
  { id: "models",       label: "Formal Models",             color: "#9E86F2" },
  { id: "human",        label: "Human Factor",               color: "#E58AA5" },
  { id: "risk",         label: "Risk & Economics",           color: "#E08A4B" },
  { id: "forensics",    label: "Forensics & Detection",      color: "#3FB68B" },
  { id: "privacy",      label: "Privacy & Data Protection",  color: "#7C9CF0" },
  { id: "crypto",       label: "Cryptography & Systems",     color: "#D46FB5" },
];

const LAWS = [
  // ---------------- FOUNDATIONAL ----------------
  {
    slug: "kerckhoffs-principle",
    title: "Kerckhoffs's Principle",
    category: "foundational",
    origin: "Auguste Kerckhoffs, 1883",
    summary: "A cryptosystem should remain secure even if everything about it, except the key, is public knowledge.",
    body: "Auguste Kerckhoffs laid out six design requirements for military ciphers in his 1883 essay La Cryptographie Militaire. The surviving principle holds that a system's security must rest entirely on the secrecy of the key, not on the secrecy of the algorithm. An attacker is assumed to have full knowledge of the system's design; the only thing standing between them and the plaintext is the key. This is the philosophical opposite of hiding your mechanism and hoping nobody looks.",
    why: "It is the reason modern cryptographic standards are published and publicly scrutinized rather than kept secret. Open algorithms that survive years of attack attempts are trusted precisely because they were never relying on obscurity.",
    related: ["shannon-maxim", "security-through-obscurity"],
  },
  {
    slug: "shannon-maxim",
    title: "Shannon's Maxim",
    category: "foundational",
    origin: "Claude Shannon, 1949",
    summary: "The enemy knows the system.",
    body: "In his 1949 paper Communication Theory of Secrecy Systems, Claude Shannon formalized cryptography as a branch of information theory and restated Kerckhoffs's assumption in a single, blunt sentence: design as though your adversary already has the blueprints. Shannon's work went further, introducing the mathematical definition of perfect secrecy and proving that the one-time pad achieves it when the key is truly random, used once, and at least as long as the message.",
    why: "It sets the baseline threat model for essentially all serious security engineering: never design a system whose safety depends on the attacker's ignorance.",
    related: ["kerckhoffs-principle", "perfect-secrecy"],
  },
  {
    slug: "cia-triad",
    title: "The CIA Triad",
    category: "foundational",
    origin: "Classical information security model",
    summary: "Confidentiality, Integrity, and Availability form the three pillars every security control ultimately serves.",
    body: "Confidentiality means information is disclosed only to authorized parties. Integrity means information and systems are not altered by unauthorized parties and remain accurate. Availability means authorized parties can access information and systems when needed. Nearly every control — encryption, access lists, backups, hashing, redundancy — maps back to protecting one or more of these three properties, and security tradeoffs are frequently a negotiation between them.",
    why: "It's the common vocabulary used to classify risk, scope incidents, and justify controls in virtually every security framework, from ISO 27001 to NIST.",
    related: ["parkerian-hexad", "least-privilege"],
  },
  {
    slug: "parkerian-hexad",
    title: "The Parkerian Hexad",
    category: "foundational",
    origin: "Donn B. Parker, 1998",
    summary: "An extension of the CIA Triad adding Possession, Authenticity, and Utility.",
    body: "Security researcher Donn Parker argued the CIA Triad was too coarse to describe real incidents. He proposed six elements: Confidentiality, Possession or Control, Integrity, Authenticity, Availability, and Utility. Possession captures cases like a stolen but still-encrypted backup tape — confidentiality is intact, but control of the asset is lost. Utility captures cases where data is technically available and intact but useless, such as an encryption key being destroyed.",
    why: "It gives incident responders sharper language for scenarios the CIA Triad alone can't cleanly classify, particularly theft, sabotage, and denial-of-use cases.",
    related: ["cia-triad"],
  },
  {
    slug: "saltzer-schroeder",
    title: "Saltzer & Schroeder's Design Principles",
    category: "foundational",
    origin: "Jerome Saltzer & Michael Schroeder, 1975",
    summary: "Eight design principles for building protected computer systems, still taught as the field's baseline.",
    body: "In The Protection of Information in Computer Systems, Saltzer and Schroeder distilled economy of mechanism (keep designs small and simple enough to verify), fail-safe defaults (deny by default), complete mediation (check every access, every time), open design (don't rely on secrecy of design), separation of privilege (require more than one condition to grant access), least privilege (grant only what's needed), least common mechanism (minimize shared components between users), and psychological acceptability (make the secure way the easy way).",
    why: "Nearly every access-control and hardening principle in use today traces back to one of these eight ideas, making the 1975 paper one of the most cited works in security engineering.",
    related: ["least-privilege", "fail-safe-defaults", "complete-mediation", "psychological-acceptability"],
  },
  {
    slug: "least-privilege",
    title: "The Principle of Least Privilege",
    category: "foundational",
    origin: "Saltzer & Schroeder, 1975",
    summary: "Every process, user, and system component should operate with the minimum access necessary to do its job, nothing more.",
    body: "Least privilege narrows the blast radius of any single compromise. A web server account that can only read the files it serves cannot be leveraged to modify the database, even if the process is fully compromised. In practice this means default-deny permissions, scoped service accounts, just-in-time elevation, and regular access reviews to strip privileges that accumulate but are never revoked.",
    why: "It is the single most cited mitigating control in breach post-mortems: over-provisioned accounts and roles are what let a minor foothold become a full compromise.",
    related: ["saltzer-schroeder", "need-to-know", "separation-of-duties"],
  },
  {
    slug: "defense-in-depth",
    title: "Defense in Depth",
    category: "foundational",
    origin: "Military strategy, adapted to computing mid-20th century",
    summary: "No single control is trusted to work; layered, independent defenses are placed so that the failure of one does not mean total compromise.",
    body: "Borrowed from military doctrine, defense in depth applies overlapping controls — network segmentation, firewalls, endpoint detection, application hardening, encryption, monitoring, and user training — so an attacker who defeats one layer still faces another. The layers are deliberately varied in kind, not just duplicated, so a single class of failure or a single stolen credential doesn't cascade through the whole stack.",
    why: "It's the architectural answer to the fact that no control is perfect; it converts a single point of failure into a series of independent obstacles.",
    related: ["swiss-cheese-model", "assume-breach"],
  },

  // ---------------- ACCESS & TRUST ----------------
  {
    slug: "zero-trust",
    title: "Zero Trust",
    category: "access",
    origin: "John Kindervag, Forrester Research, 2010",
    summary: "Never trust, always verify — no user, device, or network segment is trusted by default, even inside the perimeter.",
    body: "Zero Trust discards the older model of a hardened network perimeter with a trusted interior. Every request is authenticated, authorized, and encrypted regardless of whether it originates inside or outside the corporate network, and trust is continuously re-evaluated rather than granted once at login. Identity, device posture, and context become the control points instead of network location.",
    why: "It directly addresses lateral movement — the technique behind most large breaches, where an attacker who lands on one internal machine is implicitly trusted to reach everything else.",
    related: ["least-privilege", "assume-breach", "complete-mediation"],
  },
  {
    slug: "need-to-know",
    title: "The Need-to-Know Principle",
    category: "access",
    origin: "Military and intelligence security doctrine",
    summary: "Access to sensitive information is granted only when it is required to perform a specific, authorized task.",
    body: "Distinct from least privilege, which concerns system permissions, need-to-know concerns information itself. A cleared employee with a valid reason to access a system may still be denied specific data if their role doesn't require it. It is the organizing principle behind compartmentalization, where sensitive projects are siloed so that a single compromised individual cannot expose the whole.",
    why: "Compartmentalizing information limits how much an insider threat or a single compromised account can expose, independent of what systems they're technically able to touch.",
    related: ["least-privilege", "separation-of-duties"],
  },
  {
    slug: "separation-of-duties",
    title: "Separation of Duties",
    category: "access",
    origin: "Accounting and auditing controls, adapted to IT security",
    summary: "Critical tasks are split among multiple people so that no single individual can complete a sensitive action alone.",
    body: "A developer who can write code should not also be the one who approves and deploys it to production. A person who can initiate a wire transfer should not also be able to approve it. Splitting the steps of a sensitive process across roles forces collusion — rather than a single insider action or a single compromised account — to cause serious harm, and creates a natural audit trail.",
    why: "It is the primary structural defense against insider fraud and against a single compromised credential being sufficient to cause catastrophic damage.",
    related: ["need-to-know", "least-privilege"],
  },
  {
    slug: "fail-safe-defaults",
    title: "Fail-Safe Defaults",
    category: "access",
    origin: "Saltzer & Schroeder, 1975",
    summary: "Access decisions should default to denial; permission must be explicitly granted rather than explicitly revoked.",
    body: "A system built on fail-safe defaults denies any request that isn't specifically allowed, so gaps in configuration fail closed rather than open. Its opposite — a default-allow posture that relies on explicitly blocking bad actors — quietly grants access to anything nobody thought to restrict, which is precisely how misconfigurations turn into breaches.",
    why: "Misconfiguration is one of the most common root causes in cloud breaches; a default-deny posture converts a missed rule into a denied request instead of an open door.",
    related: ["saltzer-schroeder", "complete-mediation"],
  },
  {
    slug: "complete-mediation",
    title: "Complete Mediation",
    category: "access",
    origin: "Saltzer & Schroeder, 1975",
    summary: "Every single access to every resource must be checked for authorization — not just the first time.",
    body: "It's not enough to check permissions once, cache the result, and assume it still holds later. Complete mediation requires that every access attempt be validated, because privileges, roles, and object states change over time. A classic violation is a system that checks a file's permissions when it's opened but not on subsequent reads, letting a since-revoked user keep reading through an open handle.",
    why: "Caching stale authorization decisions is a recurring root cause of time-of-check-to-time-of-use (TOCTOU) vulnerabilities and privilege-revocation bugs.",
    related: ["zero-trust", "saltzer-schroeder"],
  },
  {
    slug: "assume-breach",
    title: "Assume Breach",
    category: "access",
    origin: "Adopted widely across enterprise security programs, 2010s",
    summary: "Design and operate systems as though an attacker is already inside, rather than only trying to keep them out.",
    body: "Assume breach shifts investment from purely preventive controls toward detection, containment, and rapid recovery. It asks: if an attacker already has a foothold, how quickly can we detect the anomaly, how far can they move before something notices, and how fast can we contain and recover? This mindset underlies practices like continuous monitoring, micro-segmentation, and regular tabletop incident-response exercises.",
    why: "Prevention alone has a poor track record against a sufficiently resourced or patient attacker; assuming breach forces investment in the detection and response capabilities that actually limit damage.",
    related: ["zero-trust", "defense-in-depth", "defenders-dilemma"],
  },

  // ---------------- FORMAL MODELS ----------------
  {
    slug: "bell-lapadula",
    title: "The Bell–LaPadula Model",
    category: "models",
    origin: "David Bell & Leonard LaPadula, 1973",
    summary: "A formal confidentiality model: no reading up, no writing down.",
    body: "Developed for the U.S. Department of Defense, Bell–LaPadula formalizes multilevel security using two rules. The Simple Security Property prevents a subject from reading data classified above their clearance ('no read up'). The Star Property prevents a subject from writing data down to a lower classification level ('no write down'), which stops classified information from leaking to a less-trusted context even by an authorized, well-intentioned user.",
    why: "It's the formal basis for mandatory access control in classified government and military systems, and the ancestor of many modern data-classification schemes.",
    related: ["biba-model", "clark-wilson"],
  },
  {
    slug: "biba-model",
    title: "The Biba Integrity Model",
    category: "models",
    origin: "Kenneth Biba, 1977",
    summary: "The integrity counterpart to Bell–LaPadula: no reading down, no writing up.",
    body: "Where Bell–LaPadula protects confidentiality, Biba protects integrity by inverting the rules: a subject cannot read data from a lower integrity level ('no read down') and cannot write to a higher integrity level ('no write up'). This prevents low-integrity or untrusted input from contaminating trusted, high-integrity data and processes.",
    why: "It's the theoretical basis for practices like not letting untrusted user input directly modify trusted configuration or system files.",
    related: ["bell-lapadula", "clark-wilson"],
  },
  {
    slug: "clark-wilson",
    title: "The Clark–Wilson Model",
    category: "models",
    origin: "David Clark & David Wilson, 1987",
    summary: "A commercial integrity model built around well-formed transactions and separation of duties, rather than security labels.",
    body: "Clark and Wilson observed that military-style classification models didn't map well to commercial needs like accounting integrity. Their model requires that data only be modified through well-formed transactions — constrained procedures rather than arbitrary writes — and enforces separation of duties between the person who prepares a transaction and the person who certifies it, mirroring double-entry bookkeeping controls.",
    why: "It underlies modern financial-system controls and the broader software engineering principle that data should never be mutated by arbitrary, unaudited paths.",
    related: ["biba-model", "separation-of-duties"],
  },
  {
    slug: "brewer-nash",
    title: "The Brewer–Nash Model (Chinese Wall)",
    category: "models",
    origin: "David Brewer & Michael Nash, 1989",
    summary: "Access is restricted dynamically based on a user's history, to prevent conflicts of interest.",
    body: "Designed for financial and consulting environments, the Chinese Wall model allows a user to access any single dataset initially, but once they've accessed data belonging to one client in a competitive group, access to competing clients' data in the same group is automatically blocked. Unlike static classification models, the access rules change based on what the user has already done.",
    why: "It formalizes information-barrier requirements common in law, finance, and consulting, where the risk isn't classification level but conflict of interest.",
    related: ["bell-lapadula", "need-to-know"],
  },

  // ---------------- HUMAN FACTOR ----------------
  {
    slug: "weakest-link",
    title: "The Weakest Link Principle",
    category: "human",
    origin: "Attributed to Bruce Schneier and widely repeated in security literature",
    summary: "A system's overall security is bounded by its least secure component, and that component is very often a human being.",
    body: "No matter how strong the cryptography or how hardened the network, a security posture is only as strong as its weakest point of entry, and that point is disproportionately a person: a reused password, a convincing phishing email, a misconfigured permission set by a rushed admin. Attackers economize effort by targeting the path of least resistance rather than the strongest control.",
    why: "It's the rationale behind investing as heavily in security awareness, phishing simulation, and usable design as in technical controls.",
    related: ["social-engineering", "psychological-acceptability"],
  },
  {
    slug: "psychological-acceptability",
    title: "Psychological Acceptability",
    category: "human",
    origin: "Saltzer & Schroeder, 1975",
    summary: "If the secure way of doing something is harder than the insecure way, people will route around it.",
    body: "Saltzer and Schroeder argued that a security mechanism's usability is itself a security property, not a separate concern from it. Controls that impose excessive friction get bypassed, disabled, or worked around, often in ways that reintroduce more risk than the control removed. A password policy so strict that people write passwords on sticky notes is a well-known illustration.",
    why: "It's the founding argument for usable security as a discipline — the observation that unusable controls don't get better security outcomes, they get workarounds.",
    related: ["saltzer-schroeder", "weakest-link", "security-theater"],
  },
  {
    slug: "security-theater",
    title: "Security Theater",
    category: "human",
    origin: "Bruce Schneier, popularized early 2000s",
    summary: "Measures that create a feeling of improved security without meaningfully improving it.",
    body: "Security theater describes controls adopted primarily for their visibility and reassurance value rather than their measurable effect on risk. Schneier used the term extensively in critiquing post-9/11 airport security measures, but the concept generalizes: any control chosen because it looks rigorous, satisfies a checkbox, or reassures stakeholders, while doing little to change an attacker's actual cost of success.",
    why: "Recognizing security theater helps organizations redirect budget from reassuring but low-value controls toward measures that actually raise the cost of a successful attack.",
    related: ["psychological-acceptability", "precautionary-principle"],
  },
  {
    slug: "peltzman-effect",
    title: "The Peltzman Effect (Risk Compensation)",
    category: "human",
    origin: "Sam Peltzman, 1975",
    summary: "People often adjust their behavior to be riskier in response to safety measures, offsetting some of the intended benefit.",
    body: "Economist Sam Peltzman found that safety regulations for automobiles were partly offset by drivers who felt safer taking more risks. In security, the analogous pattern shows up when users behave less cautiously because a control is present: clicking more freely because 'the spam filter will catch it,' or reusing passwords because 'we have multi-factor authentication anyway.'",
    why: "It's a caution against assuming a control's theoretical benefit will fully materialize once real human behavior adapts around it.",
    related: ["psychological-acceptability", "weakest-link"],
  },
  {
    slug: "social-engineering",
    title: "The Human Firewall Fallacy",
    category: "human",
    origin: "Security awareness literature, widely discussed",
    summary: "No amount of training makes humans a reliable substitute for technical controls against social engineering.",
    body: "Security awareness training reduces, but does not eliminate, susceptibility to phishing, pretexting, and other social engineering tactics, because these attacks are specifically engineered to exploit normal, adaptive human behaviors like trust, urgency, and authority — not carelessness. Framing users as a 'firewall' sets an expectation of perfect vigilance that no population of humans can sustain indefinitely.",
    why: "It argues for layering technical controls — phishing-resistant authentication, email filtering, transaction verification — behind training, rather than relying on training alone.",
    related: ["weakest-link", "dunning-kruger-security"],
  },
  {
    slug: "dunning-kruger-security",
    title: "Dunning–Kruger in Security Confidence",
    category: "human",
    origin: "David Dunning & Justin Kruger, 1999, applied to security practice",
    summary: "People with the least security knowledge tend to be the most confident in their own judgment about threats.",
    body: "The general Dunning–Kruger effect — that limited knowledge in a domain correlates with inflated self-assessment of competence in it — shows up repeatedly in security contexts: users confident they can 'spot' a phishing email, or developers confident their homegrown authentication scheme is sound. Genuine expertise tends to correlate with more calibrated caution, not less.",
    why: "It's a recurring justification for mandatory security review processes rather than relying on individual judgment calls, however confident, about what is and isn't safe.",
    related: ["social-engineering", "weakest-link"],
  },

  // ---------------- RISK & ECONOMICS ----------------
  {
    slug: "gordon-loeb",
    title: "The Gordon–Loeb Model",
    category: "risk",
    origin: "Lawrence Gordon & Martin Loeb, 2002",
    summary: "The optimal amount to spend on protecting an information asset is a fraction of the expected loss from its breach — and diminishing returns set in well before 100% protection.",
    body: "Gordon and Loeb modeled information security investment mathematically and found that spending should be calibrated to expected loss, and that the economically optimal level of investment is typically no more than roughly a third of the expected loss from a breach, because protection has sharply diminishing marginal returns as it approaches perfection. Spending far beyond that point buys little additional risk reduction for the cost.",
    why: "It's one of the few widely cited quantitative frameworks for justifying security budgets in economic terms rather than intuition or fear.",
    related: ["defenders-dilemma", "precautionary-principle"],
  },
  {
    slug: "defenders-dilemma",
    title: "The Defender's Dilemma",
    category: "risk",
    origin: "Widely used framing in security strategy literature",
    summary: "A defender must protect every possible entry point; an attacker only needs to find one that fails.",
    body: "This structural asymmetry defines most of offensive-versus-defensive security economics. A defender's cost scales with the size of their attack surface — every system, endpoint, and process must be secured — while an attacker's cost is bounded by the effort to find a single working path in. The asymmetry is why attackers so often prevail against well-resourced organizations: they need one success, defenders need to prevent all failures.",
    why: "It's the core argument for attack-surface reduction and for prioritizing detection and response over the impossible goal of zero vulnerabilities.",
    related: ["attack-surface-reduction", "assume-breach", "gordon-loeb"],
  },
  {
    slug: "pareto-vulnerabilities",
    title: "The Pareto Principle Applied to Vulnerabilities",
    category: "risk",
    origin: "Vilfredo Pareto, 1896, applied to vulnerability management",
    summary: "A small fraction of known vulnerabilities account for the large majority of real-world exploitation.",
    body: "Vulnerability and exploit data repeatedly shows a heavily skewed distribution: a minority of disclosed vulnerabilities — often those with public exploit code, network reachability, and low complexity — are responsible for most successful attacks, while a long tail of theoretically exploitable flaws is rarely if ever used in practice. Modern vulnerability prioritization frameworks lean on this pattern to triage patching effort.",
    why: "It's the statistical basis for risk-based patch prioritization (such as exploit-prediction scoring) instead of attempting to patch every CVE with equal urgency.",
    related: ["n-day-window", "attack-surface-reduction"],
  },
  {
    slug: "precautionary-principle",
    title: "The Precautionary Principle",
    category: "risk",
    origin: "Environmental and public-health policy, adapted to security risk",
    summary: "When an action carries a credible risk of severe, irreversible harm, the burden of proof falls on showing it's safe, not on showing it's dangerous.",
    body: "Borrowed from environmental and public health policy, the precautionary principle is invoked in security contexts involving catastrophic or irreversible outcomes — critical infrastructure, safety systems, or data that can never be un-leaked once exposed. Rather than waiting for proof of exploitation, controls are applied proactively because the cost of being wrong is asymmetric: too high to wait and see.",
    why: "It's frequently invoked to justify conservative controls around systems where a single failure could be catastrophic, even absent a demonstrated active threat.",
    related: ["security-theater", "gordon-loeb"],
  },
  {
    slug: "hanlons-razor-ir",
    title: "Hanlon's Razor in Incident Response",
    category: "risk",
    origin: "Popularized by Robert J. Hanlon; widely applied in IR practice",
    summary: "Never attribute to malice what is adequately explained by carelessness or error.",
    body: "During an incident, the instinct to assume a sophisticated, deliberate attack can misdirect investigation and response. Hanlon's Razor is a working default in incident response: start by ruling out misconfiguration, human error, and system failure before assuming a targeted adversary, since those mundane causes are statistically far more common than deliberate sabotage.",
    why: "It helps investigators avoid over-engineering a response to a simple misconfiguration, and keeps root-cause analysis grounded in the most probable explanation first.",
    related: ["occams-razor-threat", "swiss-cheese-model"],
  },
  {
    slug: "occams-razor-threat",
    title: "Occam's Razor in Threat Modeling",
    category: "risk",
    origin: "William of Ockham, medieval philosophy; applied to threat analysis",
    summary: "Among competing explanations for suspicious activity, the simplest one consistent with the evidence is usually correct.",
    body: "Applied to security analysis, Occam's Razor cautions against reaching for exotic nation-state theories when a simpler explanation — a misfired scheduled task, a testing script left running, an expired certificate — fits the same evidence. It doesn't rule out sophisticated threats, but it sets the order in which hypotheses should be tested.",
    why: "It keeps triage efficient by directing analysts to rule out mundane, high-probability causes before investing scarce investigative time in elaborate ones.",
    related: ["hanlons-razor-ir"],
  },

  // ---------------- FORENSICS & DETECTION ----------------
  {
    slug: "locards-exchange",
    title: "Locard's Exchange Principle",
    category: "forensics",
    origin: "Edmond Locard, early 20th century",
    summary: "Every contact leaves a trace — applied to digital forensics, every intrusion leaves some artifact behind.",
    body: "Forensic pioneer Edmond Locard's foundational principle of physical evidence — that a perpetrator will both bring something into a crime scene and leave with something from it — translates directly to digital environments. Attackers leave log entries, timestamps, memory artifacts, altered file metadata, or network traces, even when they actively try to cover them. Forensic investigation is largely the discipline of finding that trace.",
    why: "It's the theoretical foundation for the entire practice of digital forensics and incident reconstruction: the assumption that a sufficiently thorough search will find evidence of what happened.",
    related: ["swiss-cheese-model"],
  },
  {
    slug: "cohens-theorem",
    title: "Cohen's Theorem on Undecidable Virus Detection",
    category: "forensics",
    origin: "Fred Cohen, 1987",
    summary: "No algorithm can perfectly determine, for every possible program, whether it is a virus.",
    body: "Fred Cohen, who coined the term 'computer virus' in his doctoral research, proved that the general problem of detecting whether an arbitrary program is malicious is undecidable — a direct consequence of the halting problem from computability theory. There is no single algorithm that can flawlessly classify all possible programs as malicious or benign in every case.",
    why: "It's why antivirus and malware detection has always relied on heuristics, signatures, sandboxing, and behavioral analysis rather than a single perfect detection algorithm — perfect detection is mathematically impossible, not just currently unsolved.",
    related: ["swiss-cheese-model"],
  },
  {
    slug: "swiss-cheese-model",
    title: "The Swiss Cheese Model",
    category: "forensics",
    origin: "James Reason, 1990",
    summary: "Accidents and breaches occur when holes in multiple independent layers of defense happen to align.",
    body: "Psychologist James Reason developed this model to explain organizational accidents in fields like aviation and medicine, and it maps directly onto security incidents. Picture each layer of defense as a slice of Swiss cheese with random holes representing latent weaknesses. Most of the time the holes in different layers don't line up, and a threat is stopped somewhere along the way. A serious breach happens on the rare occasion the holes align across every layer at once.",
    why: "It explains why major breaches usually involve a chain of small failures rather than one dramatic one, and reinforces the value of independent, varied layers of defense.",
    related: ["defense-in-depth", "locards-exchange"],
  },
  {
    slug: "bathtub-curve",
    title: "The Bathtub Curve of Vulnerability Lifecycle",
    category: "forensics",
    origin: "Reliability engineering, adapted to vulnerability management",
    summary: "Software risk over time traces a U-shape: high early volatility, a long stable middle, then rising risk as it ages.",
    body: "Borrowed from reliability engineering's failure-rate curve for physical components, this model describes how a piece of software's vulnerability exposure often follows a similar U-shaped pattern: high early on as new, unpatched flaws surface after release, a long relatively stable middle life as major issues are found and fixed, then rising risk again as the software ages, loses vendor support, and accumulates unpatched technical debt.",
    why: "It informs decisions about when software has reached end-of-life risk levels that justify replacement rather than continued patching.",
    related: ["n-day-window"],
  },

  // ---------------- PRIVACY & DATA PROTECTION ----------------
  {
    slug: "privacy-by-design",
    title: "Privacy by Design",
    category: "privacy",
    origin: "Ann Cavoukian, 1990s; formalized 2009",
    summary: "Privacy must be embedded into the design of systems from the start, not bolted on afterward.",
    body: "Former Ontario Information and Privacy Commissioner Ann Cavoukian articulated seven foundational principles: be proactive not reactive; make privacy the default setting; embed privacy into design; retain full functionality (positive-sum, not zero-sum); ensure end-to-end security; maintain visibility and transparency; and respect user privacy by keeping the design user-centric. The framework has since been referenced in data protection regulation internationally.",
    why: "It reframed privacy from a compliance afterthought into an engineering requirement, influencing regulations like the GDPR's 'data protection by design' provision.",
    related: ["data-minimization", "purpose-limitation", "fipps"],
  },
  {
    slug: "contextual-integrity",
    title: "Contextual Integrity",
    category: "privacy",
    origin: "Helen Nissenbaum, 2004",
    summary: "Privacy isn't about secrecy or control alone — it's about information flowing in ways appropriate to the context it was shared in.",
    body: "Philosopher Helen Nissenbaum argued that privacy violations occur not simply when information is disclosed, but when it flows in a way that breaks the norms of the context in which it was originally shared. Medical information shared with a doctor moving to an insurer, or a purchase history shared with a retailer moving to a data broker, violates contextual norms even if no single disclosure was technically improper.",
    why: "It's become a foundational lens in privacy law and technology policy for evaluating data flows, because it explains privacy harms that pure secrecy or consent-based models miss.",
    related: ["mosaic-theory", "purpose-limitation"],
  },
  {
    slug: "data-minimization",
    title: "The Data Minimization Principle",
    category: "privacy",
    origin: "Codified widely, including in the GDPR (Article 5)",
    summary: "Collect only the data strictly necessary for a stated purpose, and retain it only as long as that purpose requires.",
    body: "Data minimization treats unnecessary data as a liability rather than a future asset. Every field collected, and every day it is retained beyond necessity, is additional exposure in the event of a breach and additional obligation under data protection law. It stands in direct tension with a 'collect everything, might be useful someday' approach to data strategy.",
    why: "It directly limits breach impact — data that was never collected cannot be stolen — and is a binding legal requirement in many data protection regimes.",
    related: ["privacy-by-design", "purpose-limitation"],
  },
  {
    slug: "purpose-limitation",
    title: "The Purpose Limitation Principle",
    category: "privacy",
    origin: "Codified in the GDPR and earlier OECD privacy guidelines",
    summary: "Personal data collected for one stated purpose should not be repurposed for an incompatible one without new consent or legal basis.",
    body: "Purpose limitation requires organizations to specify why data is being collected at the point of collection, and constrains later use to that stated purpose or a compatible one. Using data gathered for account security, for example, to build an advertising profile without a new legal basis violates this principle even if the original collection was legitimate.",
    why: "It closes the gap where data collected for a legitimate, narrow reason quietly expands into uses the person never agreed to.",
    related: ["data-minimization", "contextual-integrity", "fipps"],
  },
  {
    slug: "fipps",
    title: "The Fair Information Practice Principles (FIPPs)",
    category: "privacy",
    origin: "U.S. Department of Health, Education, and Welfare, 1973; refined by the OECD, 1980",
    summary: "A foundational set of principles — notice, choice, access, accuracy, security, accountability — underlying most modern privacy law.",
    body: "First articulated in a 1973 U.S. government report on automated data systems, the FIPPs established that individuals should be told what data is collected about them, given some choice over its use, able to access and correct it, and that data holders should secure it and be accountable for its handling. The OECD's 1980 privacy guidelines built on the same core ideas for an international audience.",
    why: "Nearly every subsequent privacy law — from the EU's Data Protection Directive to the GDPR to U.S. state privacy statutes — traces its structure back to these principles.",
    related: ["privacy-by-design", "purpose-limitation"],
  },
  {
    slug: "warren-brandeis",
    title: "The Right to Privacy (Warren & Brandeis)",
    category: "privacy",
    origin: "Samuel Warren & Louis Brandeis, Harvard Law Review, 1890",
    summary: "The foundational legal argument for privacy as 'the right to be let alone.'",
    body: "Responding to intrusive tabloid journalism and the then-new technology of instant photography, Warren and Brandeis argued in a Harvard Law Review article that the common law should recognize privacy as an independent legal interest, distinct from property or reputation. Their essay is widely credited as the origin of privacy as a distinct area of American law.",
    why: "It's the intellectual ancestor of virtually all subsequent privacy law, establishing that privacy deserves legal protection in its own right, not merely as a byproduct of other rights.",
    related: ["streisand-effect", "right-to-be-forgotten"],
  },
  {
    slug: "streisand-effect",
    title: "The Streisand Effect",
    category: "privacy",
    origin: "Named after Barbra Streisand's 2003 attempt to suppress a photograph of her home",
    summary: "Attempting to suppress or hide information often draws far more attention to it than leaving it alone would have.",
    body: "The term originated when a legal attempt to remove a photograph of a private residence from a public coastline archive resulted in the image being viewed far more widely than before the lawsuit, as news of the suppression attempt spread. The pattern has since been observed repeatedly online: aggressive takedown or suppression efforts frequently amplify the very information they intend to hide.",
    why: "It's a practical caution for privacy and reputation management: heavy-handed suppression can be counterproductive, and quieter, more targeted remediation is often more effective.",
    related: ["warren-brandeis"],
  },
  {
    slug: "mosaic-theory",
    title: "The Mosaic Theory of Privacy",
    category: "privacy",
    origin: "U.S. legal doctrine, prominent in United States v. Jones, 2012",
    summary: "Individually innocuous pieces of data, when aggregated, can reveal sensitive information that no single piece disclosed.",
    body: "Mosaic theory holds that privacy analysis cannot stop at each individual data point in isolation. Location pings, purchase records, and browsing history may each seem harmless alone, but combined they can reconstruct a detailed, sensitive picture of a person's habits, relationships, health, or beliefs. U.S. courts have invoked the theory when evaluating whether aggregated surveillance data requires a warrant even if each individual data point would not.",
    why: "It's central to modern arguments about metadata and aggregated data collection, which is frequently defended as harmless precisely because no single data point looks sensitive.",
    related: ["contextual-integrity"],
  },
  {
    slug: "nothing-to-hide",
    title: "The Nothing-to-Hide Fallacy",
    category: "privacy",
    origin: "Widely rebutted in privacy scholarship, notably by Daniel Solove, 2007",
    summary: "The argument 'I have nothing to hide, so I have nothing to fear from surveillance' misidentifies what privacy protects against.",
    body: "Legal scholar Daniel Solove's influential critique argues that privacy harms aren't limited to exposing wrongdoing. Aggregated data enables discrimination, chilling effects on lawful speech and association, errors that are costly to correct, and power imbalances between data holders and individuals — none of which require the individual to have done anything wrong. Privacy, in this view, is a structural check on the power that comes with holding information, not a shield solely for secrets.",
    why: "It reframes privacy debates away from individual guilt or innocence and toward the systemic risks of concentrated data and surveillance power.",
    related: ["mosaic-theory", "contextual-integrity"],
  },
  {
    slug: "right-to-be-forgotten",
    title: "The Right to Be Forgotten",
    category: "privacy",
    origin: "Established by the Court of Justice of the European Union, 2014; codified in the GDPR",
    summary: "Individuals have a qualified right to have certain personal data about them erased or delisted, even if it was lawfully published.",
    body: "The CJEU's 2014 ruling in Google Spain SL v. AEPD established that search engines could be required to delist links to accurate but outdated or irrelevant personal information when balanced against the public's interest in the information. The GDPR later codified a broader 'right to erasure,' allowing individuals to request deletion of their data under specified conditions.",
    why: "It's one of the clearest examples of privacy law asserting that data relevance and consent can expire over time, even when the original publication was lawful.",
    related: ["warren-brandeis", "data-minimization"],
  },

  // ---------------- CRYPTOGRAPHY & SYSTEMS ----------------
  {
    slug: "perfect-secrecy",
    title: "Perfect Secrecy and the One-Time Pad",
    category: "crypto",
    origin: "Claude Shannon, 1949",
    summary: "A cipher achieves mathematically perfect secrecy only when the key is truly random, used exactly once, and as long as the message.",
    body: "Shannon proved that a ciphertext produced this way reveals absolutely no information about the plaintext to an adversary with unlimited computing power — not just 'hard to break,' but information-theoretically unbreakable. In practice, one-time pads are rarely usable because generating, distributing, and never reusing keys as long as every message is enormously impractical, which is why virtually all modern cryptography instead relies on computational security rather than perfect secrecy.",
    why: "It establishes the theoretical upper bound that all practical cryptography is measured against, and clarifies why 'unbreakable' is a much stronger and rarer claim than 'currently secure.'",
    related: ["shannon-maxim", "moores-law-crypto"],
  },
  {
    slug: "moores-law-crypto",
    title: "Moore's Law and Cryptographic Half-Life",
    category: "crypto",
    origin: "Gordon Moore, 1965, applied to cryptanalysis",
    summary: "As computing power grows, key lengths and algorithms considered secure today have a shrinking shelf life.",
    body: "Moore's original observation — that transistor density, and by extension computing power, roughly doubles at a regular interval — has a direct consequence for cryptography: brute-force attack costs fall over time even without any flaw in the algorithm itself. This is why key lengths and hash functions considered adequate decades ago (56-bit DES keys, MD5) are now considered broken or trivially attackable, and why standards bodies periodically mandate longer keys and newer algorithms.",
    why: "It's the reason cryptographic agility — the ability to upgrade algorithms and key lengths without a system redesign — is treated as a first-class design requirement, not an afterthought.",
    related: ["perfect-secrecy"],
  },
  {
    slug: "security-through-obscurity",
    title: "Security Through Obscurity Is Not Security",
    category: "crypto",
    origin: "Corollary of Kerckhoffs's Principle",
    summary: "Hiding how a system works is not a substitute for making it actually resistant to attack.",
    body: "This is the practical, negative restatement of Kerckhoffs's Principle: obscurity can raise the initial cost of an attack, but it does not make a system secure, because the underlying design will eventually be discovered — through reverse engineering, insider disclosure, or independent rediscovery — and a system that only worked because nobody knew how it functioned fails completely once that knowledge is out.",
    why: "It's regularly invoked to push back on proposals to keep a security mechanism's design secret instead of subjecting it to open review and testing.",
    related: ["kerckhoffs-principle", "shannon-maxim"],
  },
  {
    slug: "attack-surface-reduction",
    title: "Attack Surface Reduction",
    category: "crypto",
    origin: "General systems security principle",
    summary: "Every exposed interface, open port, running service, and line of reachable code is a potential entry point — minimize what's exposed.",
    body: "Attack surface reduction is the practice of systematically eliminating unnecessary exposure: disabling unused services, closing unneeded ports, removing default accounts, restricting network reachability, and simplifying code paths that handle untrusted input. It doesn't make remaining components more secure on their own, but it reduces the number of places an attacker can probe in the first place.",
    why: "It directly counters the Defender's Dilemma: an attacker only needs one working entry point, so shrinking the number of possible entry points shrinks their odds.",
    related: ["defenders-dilemma", "least-privilege"],
  },
  {
    slug: "metcalfes-law-risk",
    title: "Metcalfe's Law of Network Risk",
    category: "crypto",
    origin: "Robert Metcalfe, 1980s, applied to security exposure",
    summary: "As a network's value grows roughly with the square of its connected nodes, so does its exposure — more connections mean more potential paths for an attacker.",
    body: "Metcalfe's original law described the value of a telecommunications network as proportional to the square of its number of connected users. Applied to security, the same growth curve describes exposure: every additional connected device, integration, or third-party API is a node that can be compromised and a potential pivot point into everything else it touches, so total attack surface tends to grow faster than the network itself.",
    why: "It's a caution against unchecked interconnection and a rationale for network segmentation, which deliberately breaks a large, densely connected network into smaller, more contained ones.",
    related: ["attack-surface-reduction", "assume-breach"],
  },
  {
    slug: "n-day-window",
    title: "The N-Day Window",
    category: "crypto",
    origin: "Vulnerability management practice",
    summary: "The period between a vulnerability's public disclosure and its patching is often more dangerous than the zero-day period before disclosure.",
    body: "Once a vulnerability and its patch are public, attackers can reverse-engineer the fix to build a working exploit, often faster than defenders can test and roll out the patch across their environment. This 'n-day' window — where the flaw is known but not yet universally patched — accounts for a large share of real-world exploitation, frequently exceeding true zero-day attacks in practice.",
    why: "It's the core argument for fast, prioritized patch management rather than treating patching as routine maintenance that can wait for a convenient cycle.",
    related: ["pareto-vulnerabilities", "bathtub-curve"],
  },
  {
    slug: "linus-law-security",
    title: "Linus's Law, Applied to Security Auditing",
    category: "crypto",
    origin: "Eric S. Raymond, 1999, describing open-source development",
    summary: "Given enough eyeballs, all bugs are shallow — including security bugs, when code is genuinely reviewed by capable, motivated reviewers.",
    body: "Eric Raymond's original formulation described open-source software development, arguing that wide peer review surfaces bugs faster than closed development. Applied to security, the principle is real but conditional: open-source code isn't automatically more secure, and history includes long-undiscovered flaws in widely used open-source libraries. The benefit materializes specifically when qualified reviewers are actually looking, not merely when source code is technically visible.",
    why: "It explains both the security argument for open source and its most common counterargument: visibility alone doesn't guarantee scrutiny, and unreviewed open code can hide flaws for years.",
    related: ["kerckhoffs-principle", "security-through-obscurity"],
  },
];
